name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  build:
    name: Build
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Compile
        run: ./gradlew compileKotlin

      - name: Run tests
        run: ./gradlew test --info

      - name: Check formatting
        run: ./gradlew spotlessCheck

      - name: Clean before build
        run: ./gradlew clean

      - name: Build
        run: ./gradlew -PprodBuild=true -Pprerelease=false :emulinker:build

      - name: Check server version
        id: server_version
        run: |
          set -euo pipefail
          VER=$(./gradlew -q -PprodBuild=true -Pprerelease=false \
                :emulinker:properties \
                | sed -n 's/^version: //p' \
                | head -n1)
          echo "server_version=$VER" >> "$GITHUB_OUTPUT"

      - name: Prepare package
        id: package
        env:
          VERSION: ${{ steps.server_version.outputs.server_version }}
        run: |
          set -euo pipefail
          mkdir -p EmuLinker-K/lib EmuLinker-K/conf
          cp -R .release/* EmuLinker-K/
          cp emulinker/src/main/i18n/* EmuLinker-K/conf/
          cp emulinker/build/libs/emulinker-k-*.jar EmuLinker-K/lib/emulinker-k.jar
          ZIP="EmuLinker-K-${VERSION}.zip"
          zip -X -r -9 "$ZIP" EmuLinker-K
          echo "zipfile=$ZIP" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmuLinker-K-${{ steps.server_version.outputs.server_version }}
          path: ${{ steps.package.outputs.zipfile }}
